modules_weight.settings:
  type: config_object
  label: 'Modules Weight settings'
  mapping:
    show_system_modules:
      type: boolean
      label: 'Define if the modules weight form should show the core modules.'
