cookies.cookies_service.*:
  type: config_entity
  label: 'COOKiES service'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    group:
      type: string
      label: 'Group'
    info:
      type: text_format
      label: 'Info'
    url:
      type: label
      translatable: true
      label: 'Url'
    consent:
      type: boolean
      label: 'Consent required'
    uuid:
      type: string
    langcode:
      type: string
      label: 'Language code'
    dependencies:
      type: config_dependencies
      label: 'Dependencies'
