<?php

/**
 * @file
 * Contains custom_commerce.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function custom_commerce_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the custom_commerce module.
    case 'help.page.custom_commerce':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom configurations to commerce module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function custom_commerce_theme() {
  return [
    'custom_commerce' => [
      'render element' => 'children',
    ],
  ];
}
